root:
  controller: App\Controllers\RootController
  paths:
    - path: /
      method: GET
      action: indexAction
      services:
        - App\Services\Service
    - path: /about
      method: GET
      action: aboutAction